### ISSUE TITLE
Button index not found

### ISSUE THREAD

**Issue by LukMercury** [piborg/Gamepad#10]
I've been getting this error when I run any script, including EventExample.py

Gamepad connected
Traceback (most recent call last):
  File "/mnt/raid1/Code/Useful/Gamepad/Gamepad.py", line 421, in addButtonPressedHandler
    if callback not in self.pressedEventMap[buttonIndex]:
KeyError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/raid1/Code/Useful/Gamepad/EventExample.py", line 64, in <module>
    gamepad.addButtonPressedHandler(buttonHappy, happyButtonPressed)
  File "/mnt/raid1/Code/Useful/Gamepad/Gamepad.py", line 424, in addButtonPressedHandler
    raise ValueError('Button %i was not found' % buttonIndex)
ValueError: Button 0 was not found

The only thing changed in EventExample.py is this:

# Wait for a connection
if not Gamepad.available(1):
    print('Please connect your gamepad...')
    while not Gamepad.available(1):
        time.sleep(1.0)
gamepad = gamepadType(1)
print('Gamepad connected')

I put "1" in the parantheses instead of default value 0.

It says "GamePad Connected" even if the GamePad is not connected.

**Comment by LukMercury** [comment]
Sorry about this, my bad, OS had just decided to change /dev/input/js1 to /dev/input/js2 and I'd forgotten to make all the changes in the code. there were three places where I had to change it, and I'd forgotten about two of them. All good, thanks!
